return {
  --   "m4xshen/hardtime.nvim",
  --   dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
  --   opts = {
  --     -- Disable hardtime when explicitly turned off
  --     disable_mouse = true,
  --     -- Prevent mashing j,k,h,l by setting a delay.
  --     max_count = 5,
  --     hint = true,
  --     notification = true,
  --     -- don't run in telescope, undotree, NvimTree, alpha, etc.
  --     disabled_filetypes = {
  --       "qf",
  --       "netrw",
  --       "NvimTree",
  --       "lazy",
  --       "mason",
  --       "oil",
  --       "undotree",
  --       "Trouble",
  --       "alpha",
  --     },
  --   },
  --   config = function(_, opts)
  --     require("hardtime").setup(opts)
  --   end,
}
